[package]
name = "lang-1"
version = "0.1.0"
authors = ["tristans2"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "lang-1"
path = "main.rs"
